main2: 
	gcc -E prog.c   //preprocessing
	gcc -S prog.c   //compilation-covert our code to assembly code
	gcc prog.c -o prog.o   //assembler converts the assembly code into binary code
	gcc prog.c   //executes the program



